### ISSUE TITLE
关于如何新增一个tabs页的疑问

### ISSUE THREAD

**Issue by arcticlin** [chanxystar/chanxy_manage_backend#1]
你好，你的代码对我非常有用。
我本身没什么react基础，希望找一个模块能够快速使用并实现我需要的功能。
现在我卡在了如何新增一个tab页上，希望你能帮助到我。
前置:
    route配置路径后，当前路径为/apitest/test。页面正常，tab正常，路由正常。
问题:
    现在我在这个页面添加一个按钮，点击按钮后，我希望能新增一个tab页并且对应的路由是/apitest/test/deatil/1(即:id)
我的代码:
    我在@/src/router/index.tsx下添加
```
<Route
  element={<CaseDetail />}
  path="/apitest/test/detail/:id">
</Route>
```
    
并在页面的按钮上添加

```
onClick(()=>dispatch({type: "tab/navigate", payload: {
        key: "/apitest/test/detail/1",
        label: label,
      }, }))
```
结果实际的现象就是直接跳转到了/apitest/test/detail/:id页面而不是新增tab页，同时页面无法返回，只能重新访问/路径
请问我该如何做?

**Comment by chanxystar** [comment]
稍等哈，我今天会给你答复发自我的 iPhone在 2023年7月6日，下午6:08，Abel Pouros ***@***.***> 写道：﻿
你好，你的代码对我非常有用。
我本身没什么react基础，希望找一个模块能够快速使用并实现我需要的功能。
现在我卡在了如何新增一个tab页上，希望你能帮助到我。
前置:
route配置路径后，当前路径为/apitest/test。页面正常，tab正常，路由正常。
问题:
现在我在这个页面添加一个按钮，点击按钮后，我希望能新增一个tab页并且对应的路由是/apitest/test/deatil/1(即:id)
我的代码:
我在@/src/router/index.tsx下添加
<Route
  element={<CaseDetail />}
  path="/apitest/test/detail/:id">
</Route>

并在页面的按钮上添加
onClick(()=>dispatch({type: "tab/navigate", payload: {
        key: "/apitest/test/detail/1",
        label: label,
      }, }))

结果实际的现象就是直接跳转到了/apitest/test/detail/:id页面而不是新增tab页，同时页面无法返回，只能重新访问/路径
请问我该如何做?

**Comment by chanxystar** [comment]
非常抱歉比较迟回复你，你这个问题提醒了我，我封装的标签页功能并没有兼容“动态路由”或者叫“参数化路由”的情况，我将在晚些时候修正这个bug，如果你现在要开发details页面，我建议你是使用抽屉或者弹窗的形式，也就是内置antd组件的Drawer或者Modal组件，至少我在我的项目中是这样做的。

Sorry for the late reply. Your question reminded me that the tab page function I encapsulated is not compatible with "dynamic route" or "parameterized route". I will fix this bug later. If you now To develop the details page, I suggest you use a drawer or pop-up window, that is, a Drawer or Modal component with built-in antd components, at least I do this in my project.

**Comment by chanxystar** [comment]
我建议这样封装详情抽屉：（I recommend encapsulating the details drawer like this）：
```typescript
import { Drawer} from "antd";
import { memo } from "react";
interface Props {
  open: boolean;
  id: number;
  onClose: () => void;
}

function Details({ open = false, id, onClose }: Props) {
  //Data request and other data processing based on id
  return (
    <Drawer
      title="caseDetails"
      placement="right"
      width={"calc(100vw - 200px)"}
      onClose={onClose}
      open={open}
    >
     {'your content'}
   </Drawer>)
}
export default memo(Details);
```

**Comment by arcticlin** [comment]
感谢你的回复。那我暂时先这么处理了。
因为我比较少了解react没有能力去帮你新增这方面的功能，很抱歉，但是个人感觉对于一个多标签页的中后台管理项目，感觉能动态新增标签还是挺刚需的~

**Comment by chanxystar** [comment]
谢谢你的建议，因为这个是我公司项目抽象出来的模板，所以我并没有考虑到这种路由模式的情况，我会尽快修复这个bug，并且精简一些代码，git一个更新的版本上来

**Comment by chanxystar** [comment]
不好意思这周有点忙，已经上线了修复版本，完美解决了这个问题，你可以正常的使用useNavigate()钩子进行跳转，无需调用store中的方法，就可以出现tab

**Comment by arcticlin** [comment]
感谢你的方案，用起来确实方便了很多。
但是我还有一个疑问想请教一下。
我测试了一下:
如果要使用navigate()去打开一个新的tab页，需要在@/src/router/routes.tsx中的baseRoutes里去配置一个具体的路由并使用hidden: true来隐藏它在侧边栏的显示。
```
{
        path: "/info/product/1",
        element: <div>商品:1</div>,
        name: "product",
        meta: {
          hidden: true,
          title: "货品信息1",
        },
      },
```
但是如果我在baseRoutes里配置的是一个参数路由，则当使用navigate("/info/product/1")时，好像就没办法触发新建tan页了，页面只会在当前tab页渲染element数据。
```
{
        path: "/info/product/:id",
        element: <div>商品:1</div>,
        name: "product",
        meta: {
          hidden: true,
          title: "货品信息1",
        },
      },
```
我该怎么去解决这个问题呢?

---
补充一下，我研究一下，并在@/src/utils/router.ts里的getRoute方法中补充了个参数匹配的，看起来好像能实现我的需求了，能帮忙看一下我添加的和您的代码会有什么冲突吗?
```
export const getRoute = (
  path: string,
  routes: BaseRoute[]
): 
    ...
    const route = routes[i];
    // 使用react-router-dom的matchPath方法对route里的path和传入的path进行匹配
    if (route.path.includes(":")) {
      const match = matchPath({ path: route.path, end: false }, path);
      if (match) {
        const dynamicRoute = { ...route, path: match.pathname }
        return dynamicRoute
      }

    }
   ...
    if (route.path === path) {

      return route;
    }
   ...
  }

  return undefined;
};
```

**Comment by chanxystar** [comment]
看起来是没啥问题的，需要我给你开设权限吗，开启新分支，然后git上来看看

**Comment by chanxystar** [comment]
非常感谢你的补充，我已经把你的idea加入到代码中了，我邀请你进入这个仓库，以证明你对这个项目有贡献！你的能力比我强，我很羡慕你的代码阅读能力
